# Generated by Django 3.2.4 on 2021-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='edad',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='clase',
            name='apellido',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='clase',
            name='id',
            field=models.PositiveBigIntegerField(primary_key=True, serialize=False),
        ),
    ]
