# Generated by Django 3.2.4 on 2021-07-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='isStudent',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='users',
            name='isTeacher',
            field=models.BooleanField(default='False'),
        ),
    ]
