# Generated by Django 3.2.4 on 2021-07-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='Telefono',
            field=models.BigIntegerField(default=0),
        ),
    ]
