# Generated by Django 3.2.4 on 2021-07-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_estudiante_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='celular',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
