# Generated by Django 3.2.4 on 2021-07-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_auto_20210709_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telefono',
            field=models.BooleanField(default='False'),
        ),
    ]
