# Generated by Django 3.2.4 on 2021-06-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0002_auto_20210624_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='profesores',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(default='', max_length=300)),
                ('edad', models.CharField(default='0', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='materia',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('nombre_materia', models.CharField(max_length=200)),
                ('docentes', models.ManyToManyField(to='clase.profesores')),
            ],
        ),
    ]
