# Generated by Django 3.2.4 on 2021-07-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0003_alter_profesores_celular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesores',
            old_name='celular',
            new_name='Telefono',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='Telefono',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
