# Generated by Django 3.2.4 on 2021-08-12 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0004_auto_20210729_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='alumno_materia',
        ),
        migrations.AddField(
            model_name='materia',
            name='curso_materia',
            field=models.ForeignKey(default='no hay', on_delete=django.db.models.deletion.CASCADE, to='clase.curso'),
        ),
    ]
