# Generated by Django 3.2.4 on 2021-08-12 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0005_auto_20210812_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='alumno_curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='alumno_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clase.curso'),
        ),
    ]
