# Generated by Django 3.2.4 on 2021-08-12 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0006_auto_20210812_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='alumno_curso',
            new_name='curso_id',
        ),
    ]
