# Generated by Django 3.2.4 on 2021-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0007_rename_alumno_curso_estudiante_curso_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
