# Generated by Django 3.2.4 on 2021-08-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0008_alter_materia_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='docente_curso',
            new_name='id_curso',
        ),
    ]
