# Generated by Django 3.2.4 on 2021-08-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0009_rename_docente_curso_curso_id_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='id_curso',
            field=models.ManyToManyField(to='clase.profesores'),
        ),
    ]
