# Generated by Django 3.2.4 on 2021-08-19 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0010_materia_id_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materia',
            old_name='id_curso',
            new_name='id_profesor',
        ),
    ]
