# Generated by Django 3.2.4 on 2021-08-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0011_rename_id_curso_materia_id_profesor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id_curso',
        ),
    ]
